export type Level = 'Fresher' | 'Junior' | 'Mid-level' | 'Senior' | 'Lead / Strategic'
export type CaseStudy = { id: string; title: string; domain: string; level: Level; duration: number | null; skills: string[]; status: 'Mô phỏng' | 'Chờ biên tập'; question: string; description: string; background: string }

export const cases: CaseStudy[] = [
  { id:'revenue-checkout', title:'Doanh thu giảm: ít khách hay ít người mua?', domain:'Thương mại điện tử', level:'Fresher', duration:6, skills:['Funnel','Doanh thu','Phân rã metric'], status:'Mô phỏng', question:'Doanh thu giảm do đâu? Bạn sẽ kiểm tra gì và xử lý ra sao?', description:'Tách doanh thu thành lượng truy cập, chuyển đổi và giá trị đơn hàng.', background:'MÔ PHỎNG · Tuần này doanh thu giảm 12%. Lượt truy cập gần như không đổi; tỷ lệ mua giảm từ 3,1% xuống 2,5%; giá trị đơn trung bình ổn định. Chưa biết thay đổi nằm ở thiết bị, kênh hay bước checkout nào.' },
  { id:'revenue-promo', title:'Khuyến mãi tăng nhưng doanh thu vẫn giảm', domain:'Thương mại điện tử', level:'Junior', duration:7, skills:['Giá trị đơn hàng','Phân khúc','Trade-off'], status:'Mô phỏng', question:'Doanh thu giảm vì thiếu đơn hay vì mỗi đơn nhỏ hơn? Có nên tăng khuyến mãi?', description:'Đọc các thành phần doanh thu trước khi đề xuất giảm giá sâu hơn.', background:'MÔ PHỎNG · Số đơn tăng 4% sau chương trình ưu đãi. Giá trị đơn trung bình giảm 18%, chi phí ưu đãi tăng; doanh thu thuần giảm 6%. Chưa có dữ liệu lợi nhuận theo nhóm khách.' },
  { id:'d7-retention', title:'Retention 7D giảm sau khi đổi onboarding', domain:'Mobile app & game', level:'Junior', duration:6, skills:['Retention','Cohort','Onboarding'], status:'Mô phỏng', question:'Nguyên nhân nào đáng kiểm tra trước? Bạn xử lý thực tế thế nào?', description:'Phân biệt trải nghiệm onboarding với thay đổi cơ cấu người dùng mới.', background:'MÔ PHỎNG · D7 retention của cohort mới giảm từ 22% xuống 18% sau một lần đổi onboarding. Lượng cài mới tăng, nhưng chưa so sánh theo kênh, phiên bản app hay mức độ hoàn tất hướng dẫn.' },
  { id:'d7-tracking', title:'D7 giảm hay sự kiện tracking bị thiếu?', domain:'Mobile app & game', level:'Mid-level', duration:7, skills:['Retention','Kiểm tra dữ liệu','Tracking'], status:'Mô phỏng', question:'Làm sao phân biệt người dùng rời đi với dữ liệu không được ghi nhận?', description:'Kiểm tra định nghĩa metric, log sự kiện và phân khúc thiết bị trước khi kết luận.', background:'MÔ PHỎNG · D7 trên dashboard giảm mạnh ở Android sau bản cập nhật. DAU tổng thể gần như giữ nguyên; sự kiện mở app ngày 7 cũng giảm, nhưng chưa đối chiếu log máy chủ và phiên bản ứng dụng.' },
  { id:'d7-acquisition', title:'Retention giảm vì sản phẩm hay vì nguồn người dùng?', domain:'Mobile app & game', level:'Junior', duration:6, skills:['Retention','Phân khúc','Acquisition'], status:'Mô phỏng', question:'Cohort nào kéo D7 xuống? Hành động nào nên thử trước?', description:'Không gộp cohort có hành vi khác nhau thành một con số trung bình.', background:'MÔ PHỎNG · D7 chung giảm 3 điểm phần trăm. Tỷ trọng người dùng từ một kênh quảng cáo mới tăng gấp đôi; D7 của các kênh cũ gần như không đổi. Chưa biết chất lượng người dùng hay cách phân bổ chiến dịch đã thay đổi.' },
  { id:'game-arpdau', title:'Người chơi vẫn hoạt động, doanh thu quảng cáo giảm', domain:'Mobile app & game', level:'Mid-level', duration:7, skills:['ARPDAU','Monetization','Phân khúc'], status:'Mô phỏng', question:'Giảm do ít lượt xem quảng cáo, fill rate hay eCPM?', description:'Chọn đúng thành phần metric trước khi thay đổi tần suất quảng cáo.', background:'MÔ PHỎNG · DAU ổn định nhưng ARPDAU quảng cáo giảm 15%. Số lượt hiển thị trên mỗi người chơi giảm nhẹ; fill rate và eCPM chưa được tách theo quốc gia, nền tảng hoặc đối tác quảng cáo.' },
  { id:'rate-hike', title:'Vì sao ngân hàng trung ương tăng lãi suất?', domain:'Kinh tế & lãi suất', level:'Junior', duration:6, skills:['Lạm phát','Chính sách tiền tệ','Trade-off'], status:'Mô phỏng', question:'Mục tiêu là gì, tác động truyền dẫn ra sao và ai chịu ảnh hưởng?', description:'Lần theo chuỗi lãi suất → vay/chi tiêu → tổng cầu và các độ trễ chính sách.', background:'MÔ PHỎNG · Một nền kinh tế giả định có lạm phát cao dai dẳng, nhu cầu nội địa mạnh và áp lực tỷ giá. Ngân hàng trung ương đang cân nhắc tăng lãi suất; tăng trưởng kinh tế có dấu hiệu chậm lại.' },
  { id:'rate-impact', title:'Tăng lãi suất: bên nào được lợi, bên nào chịu sức ép?', domain:'Kinh tế & lãi suất', level:'Mid-level', duration:8, skills:['Phân tích tác động','Phân khúc','Độ trễ'], status:'Mô phỏng', question:'Tác động khác nhau thế nào với người vay, người gửi tiết kiệm và doanh nghiệp?', description:'Phân tích đường truyền chính sách và nêu các nhóm cần theo dõi.', background:'MÔ PHỎNG · Sau đợt tăng lãi suất giả định, lãi vay mới tăng nhanh hơn lãi tiền gửi. Doanh nghiệp nhỏ phụ thuộc vốn lưu động; hộ gia đình có khoản vay lãi suất thả nổi. Chưa có dữ liệu nợ xấu hay chi tiêu.' },
  { id:'land-station', title:'Giá đất quanh khu vực quy hoạch tăng', domain:'Bất động sản', level:'Junior', duration:6, skills:['Giá chào và giá giao dịch','Định giá','Kiểm chứng giả thuyết'], status:'Mô phỏng', question:'Giá tăng thật đến đâu, động lực nào có thể đứng sau và cần xác minh gì?', description:'Tách kỳ vọng, giá rao bán và giao dịch thực trước khi kết luận về thị trường.', background:'MÔ PHỎNG · Giá rao bán quanh một ga đường sắt dự kiến tăng 15% trong ba tháng. Số tin đăng cũng tăng; chưa có dữ liệu giá giao dịch đã công chứng, tiến độ dự án hay số lô thực sự đổi chủ.' },
  { id:'land-liquidity', title:'Giá rao tăng nhưng giao dịch chững lại', domain:'Bất động sản', level:'Mid-level', duration:7, skills:['Thanh khoản','Giá giao dịch','Cung cầu'], status:'Mô phỏng', question:'Thị trường đang tăng giá hay chỉ tăng kỳ vọng của người bán?', description:'Đối chiếu thanh khoản, thời gian rao bán và giá chốt thay vì chỉ nhìn giá niêm yết.', background:'MÔ PHỎNG · Giá rao trung vị tăng 9%, lượng giao dịch giảm 30%, thời gian rao bán kéo dài. Dữ liệu hiện lấy từ tin đăng trực tuyến, chưa khử tin trùng và chưa có giá chốt.' },
  { id:'delivery-delay', title:'Tỷ lệ giao trễ tăng trong tuần này', domain:'Logistics & vận hành', level:'Fresher', duration:6, skills:['SLA','Phân khúc','Seasonality'], status:'Mô phỏng', question:'Khu vực, hãng vận chuyển hay loại đơn nào tạo ra phần tăng thêm?', description:'Khoanh vùng sự cố bằng cách phân rã metric theo tuyến, thời gian và đối tác.', background:'MÔ PHỎNG · Tỷ lệ giao đúng hẹn giảm từ 94% xuống 87%. Số đơn tăng vào cuối tuần; mức giảm tập trung ở hai tuyến liên tỉnh. Chưa có thời tiết, tải kho hay thời điểm bàn giao cho đối tác.' },
  { id:'loan-default', title:'Nợ quá hạn tăng sau khi nới tiêu chí duyệt vay', domain:'Tài chính cá nhân', level:'Senior', duration:8, skills:['Rủi ro tín dụng','Cohort','Trade-off'], status:'Mô phỏng', question:'Đây là thay đổi rủi ro thật hay khác biệt về tuổi khoản vay và cohort?', description:'Đánh giá rủi ro theo vintage, thời gian quan sát và mức độ phơi nhiễm.', background:'MÔ PHỎNG · Tỷ lệ quá hạn 30 ngày tăng ở danh mục mới sau khi tiêu chí duyệt được nới. Danh mục mới còn trẻ hơn; chưa so sánh theo điểm tín dụng, sản phẩm vay, vintage hoặc số ngày có khả năng phát sinh quá hạn.' },
  { id:'finance-library', title:'Case tài chính có nguồn công khai', domain:'Tài chính', level:'Senior', duration:null, skills:['Đọc nguồn','Giới hạn dữ liệu'], status:'Chờ biên tập', question:'Case sẽ hiển thị sau khi biên tập nguồn và dữ liệu.', description:'Thư viện đang chờ nguồn công khai và bộ dữ liệu có thể kiểm chứng. Chưa có số liệu hay kết luận được điền.', background:'Chưa có bối cảnh thực tế được xác minh.' },
]

export const skills = [
  { name:'Funnel', group:'Phân tích' }, { name:'Định nghĩa metric', group:'Nền tảng' }, { name:'Kiểm tra dữ liệu', group:'Nền tảng' }, { name:'Cohort', group:'Phân tích' }, { name:'Retention', group:'Phân tích' }, { name:'Phân khúc', group:'Phân tích' }, { name:'Seasonality', group:'Tư duy' }, { name:'Confounder', group:'Tư duy' }, { name:'Đo lường', group:'Tư duy' },
]

export const levels: {name:Level; desc:string; skills:string[]; complete:string; example:string}[] = [
  {name:'Fresher',desc:'Đọc và kiểm tra dữ liệu trước khi tính toán.',skills:['Định nghĩa metric','Grain dữ liệu','Null & duplicate','Lọc và tổng hợp'],complete:'Hoàn thành bài luyện metric, grain và kiểm tra chất lượng.',example:'Giải thích một metric có đơn vị, mẫu số và cửa sổ thời gian.'},
  {name:'Junior',desc:'So sánh nhóm và hình thành giả thuyết có thể kiểm tra.',skills:['Funnel','Cohort','Phân khúc','Đặt giả thuyết'],complete:'Dùng bằng chứng cho ít nhất hai phân khúc.',example:'Nêu giả thuyết và dữ liệu cần thiết để kiểm tra.'},
  {name:'Mid-level',desc:'Đánh giá nguyên nhân và thiết kế cách đo tác động.',skills:['Confounder','Seasonality','Thử nghiệm','Đánh giá tác động'],complete:'Đề xuất thiết kế đo lường có đối chứng hoặc phương án thay thế.',example:'Nêu rủi ro suy luận và cách giảm thiểu.'},
  {name:'Senior',desc:'Ưu tiên vấn đề và kết nối phân tích với quyết định.',skills:['Định lượng tác động','Trade-off','Thiết kế đo lường','Stakeholder'],complete:'Biến phân tích thành lựa chọn, trade-off và kế hoạch đo.',example:'Nêu quyết định, người chịu trách nhiệm và ngưỡng đánh giá.'},
  {name:'Lead / Strategic',desc:'Xây hệ thống metric và quy trình ra quyết định.',skills:['Chuẩn hóa metric','Định hướng bài toán','Ưu tiên nguồn lực','Quản trị dữ liệu'],complete:'Thiết kế tiêu chuẩn metric và nhịp review liên nhóm.',example:'Chứng minh cách tiêu chuẩn hóa cải thiện chất lượng quyết định.'},
]

export const steps = ['Tình huống','Chẩn đoán','Hành động','Tự kiểm tra']

export const caseGuides: Record<string, string> = {
  'revenue-checkout':'Ưu tiên kiểm tra funnel checkout theo thiết bị, kênh và bước thanh toán; đối chiếu lỗi thanh toán, tồn kho và thay đổi vừa phát hành. Nếu số đơn giảm thật, doanh thu và khả năng thu hồi chi phí cố định cùng giảm. Sửa đúng điểm nghẽn rồi theo dõi tỷ lệ checkout thành công và số đơn; chưa đủ dữ kiện để kết luận nguyên nhân chỉ từ doanh thu tổng.',
  'revenue-promo':'Doanh thu thuần có thể giảm vì giá trị đơn nhỏ đi dù số đơn tăng; lợi nhuận còn có thể giảm sâu hơn nếu chi phí ưu đãi tăng. Tính lãi góp sau giảm giá theo nhóm khách và sản phẩm trước khi tăng khuyến mãi. Thử ưu đãi có mục tiêu, theo dõi biên lợi nhuận và mua lại thay vì chỉ nhìn số đơn.',
  'd7-retention':'So sánh cohort trước/sau theo kênh, nền tảng và bước onboarding; kiểm tra phiên bản app và định nghĩa D7. Nếu người dùng bỏ sớm thật, giá trị vòng đời có thể giảm và chi phí thu hút khó hoàn vốn. Tìm bước rơi lớn nhất, phỏng vấn/kiểm tra hành vi rồi thử lại onboarding trên một nhóm; đo D1, D7 và hoàn tất hành động cốt lõi.',
  'd7-tracking':'Đối chiếu log client với server, event delivery, phiên bản app và múi giờ trước khi gọi đây là churn. Thiếu event làm retention báo thấp giả và dễ dẫn đến sửa sản phẩm sai hướng. Nếu tracking lỗi, khôi phục tracking/backfill nếu khả thi rồi mới đọc lại cohort; giữ cả chỉ số chất lượng dữ liệu trong dashboard.',
  'd7-acquisition':'Tách D7 theo kênh và so sánh trong từng kênh; số tổng có thể giảm chỉ vì cơ cấu người dùng dịch chuyển (hiệu ứng mix). Nếu cohort mới có chất lượng thấp, LTV/CAC và hoàn vốn quảng cáo có thể xấu đi. Kiểm tra activation, CAC và giá trị theo nguồn trước khi đổi sản phẩm hoặc dừng toàn bộ chiến dịch.',
  'game-arpdau':'Phân rã ARPDAU thành impressions/DAU, fill rate và eCPM theo quốc gia, nền tảng, đối tác. Sụt doanh thu trên mỗi người chơi có thể giảm hiệu quả kiếm tiền dù lượng người chơi không đổi. Khắc phục nút thắt phía phân phối/đối tác trước; thử thay đổi tần suất có kiểm soát và theo dõi retention cùng doanh thu.',
  'rate-hike':'Trong tình huống mô phỏng, tăng lãi suất có thể hạ nhiệt vay mượn và chi tiêu, qua đó giảm áp lực cầu và lạm phát; cũng có thể hỗ trợ kỳ vọng tỷ giá/lạm phát. Đổi lại, doanh nghiệp và hộ vay chịu chi phí vốn cao hơn, đầu tư và tăng trưởng có thể chậm lại. Đánh giá độ trễ, mức lạm phát, tỷ giá và sức khỏe tín dụng; đây không phải lời giải thích cho một quyết định chính sách cụ thể.',
  'rate-impact':'Tách người vay lãi suất thả nổi, người gửi tiết kiệm và doanh nghiệp cần vốn lưu động; mức truyền dẫn và thời điểm điều chỉnh khác nhau. Hệ quả có thể là chi tiêu yếu hơn, chi phí trả nợ cao hơn và thu nhập tiền gửi tốt hơn. Theo dõi dư nợ, nợ quá hạn và tiêu dùng theo nhóm; không suy rộng từ lãi suất niêm yết sang toàn bộ nền kinh tế.',
  'land-station':'Tin quy hoạch có thể làm kỳ vọng và giá rao tăng, nhưng chưa chứng minh giá giao dịch đã tăng hay công trình chắc chắn hoàn thành. Dùng giá chốt từ giao dịch tương đồng, khối lượng giao dịch, pháp lý và tiến độ chính thức để kiểm tra. Nếu chỉ giá rao tăng, người mua có thể định giá quá cao hoặc ôm rủi ro thanh khoản; tránh kết luận đầu tư từ tin đăng.',
  'land-liquidity':'Giá rao tăng đồng thời giao dịch giảm có thể phản ánh người bán neo kỳ vọng trong khi người mua rút lui; giá thị trường chưa thể xác định từ tin đăng. Khử tin trùng, đo thời gian rao, mức giảm giá và đối chiếu giao dịch hoàn tất. Rủi ro là thanh khoản kém và giá rao xa giá chốt; trình bày khoảng giá và độ bất định thay vì một con số chắc chắn.',
  'delivery-delay':'Phân rã đúng tuyến, ngày nhận đơn, thời điểm bàn giao kho và hãng vận chuyển; kiểm tra tải cuối tuần, thời tiết và cut-off. Giao trễ có thể kéo theo khiếu nại, hủy đơn và chi phí hoàn/ giao lại. Khoanh tuyến gây phần lớn mức giảm, phối hợp vận hành/đối tác thử phương án xử lý và theo dõi SLA, hủy đơn cùng khiếu nại.',
  'loan-default':'So sánh các khoản vay cùng vintage và đủ thời gian quan sát; tách theo điểm rủi ro, sản phẩm, khoản vay và ngày quá hạn. Nếu rủi ro tăng thật, tổn thất tín dụng và chi phí thu hồi nợ có thể tăng. Theo dõi cohort trưởng thành, kiểm định tiêu chí mới và điều chỉnh có mục tiêu; không quy toàn bộ mức tăng cho nới chuẩn khi mẫu còn trẻ.'
}
